---
- name: copy consul upstart script
  template:
    src: consul.conf.j2
    dest: /etc/init/consul.conf
    owner: "{{consul_user}}"
    group: "{{consul_group}}"
    mode: 0755

- name: add consul to path through profile.d
  template:
    src: consul.sh.j2
    dest: /etc/profile.d/consul.sh
    owner: root
    group: root
    mode: 0755

