---
- name: copy consul systemv script
  template: 
    src: 'consul-template-init.j2'
    dest: '/etc/init.d/consul-template'
    owner: '{{ consul_user }}'
    group: '{{ consul_group }}'
    mode: 0755
  notify:
    - restart consul

- name: add consul sysconfig file
  template:
    src: 'consul-template-sysconf.j2'
    dest: '/etc/sysconfig/consul-template'
    owner: '{{ consul_user }}'
    group: '{{ consul_group }}'
    mode: 0644
  notify:
    - restart consul
